# This file was generated by GoReleaser. DO NOT EDIT.
class Nifectl < Formula
  desc "Deploys, manages and scales applications"
  homepage "https://www.nife.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nifetency/nife-release/releases/download/prod-0.1.6/nifectl-prod-0.1.6-darwin-amd64.tar.gz"
      sha256 "46cf7228a83dd8a640c899897ef1c55c0192ddf468a8f1b6e98fa0594620daac"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nifetency/nife-release/releases/download/prod-0.1.6/nifectl-prod-0.1.6-darwin-amd64.tar.gz"
      sha256 "46cf7228a83dd8a640c899897ef1c55c0192ddf468a8f1b6e98fa0594620daac"
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nifetency/nife-release/releases/download/prod-0.1.6/nifectl-prod-0.1.6-linux-386.tar.gz"
      sha256 "f3b4918cb66520db2b60e70bc792d8f0abba1834e6609d5fa4076386d5aae64a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nifetency/nife-release/releases/download/prod-0.1.6/nifectl-prod-0.1.6-linux-amd64.tar.gz"
      sha256 "8e5bfc45bb1fda9da154fc0ad6cf350339b2af8ce20aeefbba9cd460bbf1414d"
    end
  end

  def install
    bin.install "nifectl"
    bin.install_symlink "nifectl" => "nife"
  end

  test do
    system "#{sbin}/nifectl version"
  end
end
