# This file was generated by GoReleaser. DO NOT EDIT.
class Nifectl < Formula
  desc "Deploys, manages and scales applications"
  homepage "https://www.nife.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nifetency/nife-release/releases/download/v0.1.5/nifectl-v0.1.5-darwin-amd64.tar.gz"
      sha256 "2a8304cc50931c424a57d73824ddd95c0f7c191c2775fd38c0586db1fa3cebe5"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nifetency/nife-release/releases/download/v0.1.5/nifectl-v0.1.5-darwin-amd64.tar.gz"
      sha256 "2a8304cc50931c424a57d73824ddd95c0f7c191c2775fd38c0586db1fa3cebe5"
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nifetency/nife-release/releases/download/v0.1.5/nifectl-v0.1.5-linux-386.tar.gz"
      sha256 "9b61b4932e0395beaf1a2f121d68f0c9438b074d33675b4be859b385ced1167d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nifetency/nife-release/releases/download/v0.1.5/nifectl-v0.1.5-linux-amd64.tar.gz"
      sha256 "35c86ac8ad63a30af61af5dbb318d934c2ec8b5344bdd77d368f63e30c734b3a"
    end
  end

  def install
    bin.install "nifectl"
    bin.install_symlink "nifectl" => "nife"
  end

  test do
    system "#{sbin}/nifectl version"
  end
end
